name: a3fe_reproduce

channels:
  - conda-forge
  - "openbiosim/label/dev"

dependencies:
    # Base depends
  - arviz
  - pandas
  - python
  - pip
  - numpy
  - matplotlib
  - scipy
  - ipython
  - pymbar<4
  - ambertools
  - biosimspace>2023.4
  - numpydoc
  - pydantic
  - nb-clean